### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by Shelly7w7** [room17/QuartzFactions#1]
Well. When ever I run command /f help or any /f it says unknown error occurred. I'm using pocket mine 1.2.10

**Comment by GiantQuartz** [comment]
How can I reproduce it? I tried to run the commands but they all work fine for me.

**Comment by Shelly7w7** [comment]
Wait is there need of factionspro or formapi or any other plugin to make it run?

**Comment by GiantQuartz** [comment]
You might want to check out [our Getting started section](https://github.com/room17/QuartzFactions/blob/master/README.md#getting-started) on our README file.
